apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zeep-orbit.fullname" . }}
  labels:
    {{- include "zeep-orbit.labels" . | nindent 4 }}
data:
  apps.yaml: |
{{ .Values.appsConfig | indent 4 }}
