apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeep-orbit.fullname" . }}
  labels:
    {{- include "zeep-orbit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zeep-orbit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zeep-orbit.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 35
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve", "--config", "/app/apps.yaml"]
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "zeep-orbit.fullname" . }}
          env:
            - name: BRAND_THEME
              value: {{ .Values.brand.theme }}
            - name: BRAND_COMPANY_NAME
              value: {{ .Values.brand.companyName | quote }}
          volumeMounts:
            - name: config
              mountPath: /app/apps.yaml
              subPath: apps.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
      volumes:
        - name: config
          configMap:
            name: {{ include "zeep-orbit.fullname" . }}
