apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zeep-orbit.fullname" . }}
  labels:
    {{- include "zeep-orbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.databaseUrl é obrigatório" .Values.secrets.databaseUrl | quote }}
  {{- range $appName, $appConfig := .Values.secrets.apps }}
  {{ upper $appName }}_JWT_SECRET: {{ required (printf "secrets.apps.%s.jwtSecret é obrigatório" $appName) $appConfig.jwtSecret | quote }}
  {{- end }}
