apiVersion: v1
kind: Service
metadata:
  name: zeep-core
  labels:
    app: zeep-core
spec:
  type: ClusterIP
  selector:
    app: zeep-core
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
