apiVersion: v1
kind: Service
metadata:
  name: zeep-orbit
  labels:
    app: zeep-orbit
spec:
  type: ClusterIP
  selector:
    app: zeep-orbit
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
