apiVersion: v2
name: zeep-orbit
description: Schema YAML → REST API automático no PostgreSQL
type: application
version: 0.1.3
appVersion: "0.1.3"
icon: https://raw.githubusercontent.com/zeeplabs/zeep-orbit/main/.github/logo.svg
keywords:
  - baas
  - rest
  - postgresql
  - api
  - low-code
home: https://github.com/zeeplabs/zeep-orbit
sources:
  - https://github.com/zeeplabs/zeep-orbit
maintainers:
  - name: zeeplabs
    url: https://github.com/zeeplabs
